---
# the main.yml file will simply be used to include necessary other task files

- include_tasks: install.yml
  with_items: "{{ users }}"
  loop_control:
    loop_var: user
  when: user.username is defined